apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
spec:
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
      - name: simulator
        image: shashiacr123.azurecr.io/simulator-service:v2
        ports:
        - containerPort: 8000
         
        env:
         - name: API_URL
           value: "http://ingestion-service.default.svc.cluster.local:9000/api/v1/telemetry/ingest"
         
   
        
